nodeSelector:
  region: LGA1

imageTag: 1.0.0

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: public
    # Setting a sharing key might save public IP addresses
    # See https://metallb.universe.tf/usage/#ip-address-sharing for more detail
    metallb.universe.tf/allow-shared-ip: default

ingress:
  enabled: true
  subdomainOverride: ""
