nodeSelector:
  region: LGA1

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - "{{.Values.nodeSelector.region}}"
            - key: gpu.nvidia.com/class
              operator: In
              values:
                - A40
                - A100_PCIE_40GB
                - A100_PCIE_80GB
                - Tesla_V100_NVLINK

imageTag: 1.0.0

service:
  type: LoadBalancer
  publicIP: true
  annotations:
    metallb.universe.tf/address-pool: public
    # Setting a sharing key might save public IP addresses
    # See https://metallb.universe.tf/usage/#ip-address-sharing for more detail
    metallb.universe.tf/allow-shared-ip: default
    external-dns.alpha.kubernetes.io/hostname: my-jupyter.tenant-test-default.coreweave.cloud

storage:
  class: nvme
  size: 30Gi
