nodeSelector:
  region: ORD1

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: public
    # Setting a sharing key might save public IP addresses
    # See https://metallb.universe.tf/usage/#ip-address-sharing for more detail
    metallb.universe.tf/allow-shared-ip: example-1

mounts: []
#- name: mount-name
#  pvc: pvc-name

ingress:
  enabled: true
  subdomainOverride: ''
