nodeSelector:
  region: LGA1

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - LGA1
            - key: gpu.nvidia.com/class
              operator: In
              values:
                - A40

imageTag: 1.0.0

service:
  type: LoadBalancer
  publicIP: true
  annotations:
    addressPool: public
    # Setting a sharing key might save public IP addresses
    # See https://metallb.universe.tf/usage/#ip-address-sharing for more detail
    allowSharedIp: default

storage:
  class: nvme
  size: 30Gi
