apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storage
spec:
  # NVMe block cloud storage volumes: https://docs.coreweave.com/storage/storage#block-storage-volumes
  storageClassName: block-nvme-{{ .Values.nodeSelector.region | lower }}
  accessModes:
    - ReadWriteMany
  {{- if .Values.resources }}
  resources: 
    requests:
      storage:
        {{- toYaml .Values.storage | nindent 4 }}
  {{- end }}