apiVersion: v1
kind: Service
metadata:
  type: {{ .Values.service.type }}
  annotations:
    {{- if .Values.service.publicIP }}
    metallb.universe.tf/address-pool: {{ .Values.service.annotations.addressPool }}
    metallb.universe.tf/allow-shared-ip: {{ .Values.service.annotations.allowSharedIp }}
    external-dns.alpha.kubernetes.io/hostname: {{.Release.Name}}.{{.Release.Namespace}}.coreweave.cloud
    {{- end }}
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}

spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - name: notebook
      port: 8888
      protocol: TCP
      targetPort: notebook
    - name: {{ .Release.Name }}
      port: 22
      protocol: TCP
      targetPort: {{ .Release.Name }}
  selector:
    app: {{ .Release.Name }}
